### ISSUE TITLE
Support multiple Raspberries

### ISSUE THREAD

**Issue by vincesima** [bhemar/raspberry-metrics#1]

**Comment by bhemar** [comment]
In my opinion, the best solution is to use template variables on Grafana:

- https://grafana.com/docs/reference/templating/

First, you have to configure Prometheus to scrape metrics from another Raspberry by adding new address in **static_configs** targets. You have to restart Prometheus to apply that change.

After that, Prometheus will have the same metrics from both Raspberries but with different labels (e.g. **instance** label).

Now you will have to create a **instance** variable on Grafana dashboard and set that variable in all dashboard queries, e.g.

`process_open_fds{instance="$instance"}`

After that, you will be able to select Raspberry instance on Grafana dashboard **dropdown**, and its metrics will be displayed.

I will convert this issue to "feature request", and it be will implemented in a week or two.

**Comment by bhemar** [comment]
Hey @vincesima , this is implemented. You can try and revert the results.
