### ISSUE TITLE
Node exporter not responding on Raspberry PI Zero

### ISSUE THREAD

**Issue by jeremehancock** [bhemar/raspberry-metrics#2]
I really appreciate you setting this up. I have tried to get it working with my Pis, but I am having an issue. Everything seems to be setup correctly, but the node exporter is not reachable for the "additional pis".

![image](https://user-images.githubusercontent.com/1692414/69909233-58ee9980-13bd-11ea-818d-1c4708bb5c12.png)

The node exporter is working for the "main pi".

I can't think of any networking issue here since all the Pis are on the same network. Any help you can provide would be appreciated. If there is any specific info I can provide please let me know. Thank you in advance for any help you may be able to provide.

**Comment by jeremehancock** [comment]
I just noticed that I get "Illegal instruction" if I run `./node_exporter` from "/opt/node-exporter/node_exporter-0.18.1.linux-armv7" on the Pi that I have setup as an "additional pi". It is a Pi Zero. When I run the same on the main pi (which is a Pi 2 model B) I get proper output.

**Comment by bhemar** [comment]
Hello!

I think that Raspberry PI Zero is using ARMv6 processor, and this playbook installs ARMv7 node exporter packages (it should work on Raspberry PI 2).

You can try to install ARMv6 packages on Raspberry PI Zero, just replace "node_exporter_download_url" value with "https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-armv6.tar.gz".

Please let me know if this works :)

Regards

**Comment by jeremehancock** [comment]
Thank you sir. That makes so much sense and fixed the issue. Funny thing is I was using the Pi Zero as a test before setting things up on my Pi cluster that is all Pi 2,3, and 4s.

I am off to the races now. Thanks again!
